version: '3.7'
services:
  web:
    image: nginx:latest
    container_name: ngnix-app
    ports:
      - 81:80
    links:
      - php-box1   
    volumes:
      - ./docker-config/default.conf:/etc/nginx/conf.d/default.conf 
      - ./../assessment-test:/var/www/assessment-test
    
  php-box1:
    build:
      context: "docker-config"
      dockerfile: Dockerfile-php
    container_name: php-box1-con
    ports:
      - 9000:9000
    volumes: 
      - ./../assessment-test:/var/www/assessment-test
      - ./docker-config/php.ini-development:/usr/local/etc/php/php.ini
    links:
      - mysql-box

  mysql-box:
    image: mysql
    container_name: demo-mysql
    environment:
      MYSQL_DATABASE: lovebinto
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: example
    
    ports:
      - 3306:3306
   
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-con
    ports:
       - 5672:5672
       - 15672:15672
    

    
  