FROM php:7.4-fpm
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install sockets  
RUN apt-get update -y && apt-get install -y libcurl4-openssl-dev && apt-get clean -y
RUN docker-php-ext-install curl
RUN apt-get -y install git
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer



    